App/Controllers/Api/AppPoolApiController.cs
using DevUtility.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace DevUtility.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class AppPoolApiController : ControllerBase
    {
        private readonly IAppPoolService _appPoolService;
        // GET: api/<AppPoolApiController>
        public AppPoolApiController(IAppPoolService appPoolService)
        {
            _appPoolService = appPoolService;
        }

        // POST api/<AppPoolApiController>
        [HttpPost("start")]
        public IActionResult Start([FromBody] string name)
        {
            var result = _appPoolService.StartAppPoolByName(name);
            if (result != null)
            {
                return Ok(result);
            }

            return BadRequest(result);
        }

        // POST api/<AppPoolApiController>
        [HttpPost("stop")]
        public IActionResult Stop([FromBody] string name)
        {
            var result = _appPoolService.StopAppPoolByName(name);
            if (result != null)
            {
                return Ok(result);
            }

            return BadRequest(result);
        }

        // POST api/<AppPoolApiController>
        [HttpPost("recycle")]
        public IActionResult Recycle([FromBody] string name)
        {
            var result = _appPoolService.RecycleAppPoolByName(name);
            if (result != null)
            {
                return Ok(result);
            }

            return BadRequest(result);
        }

    }
}

App/Controllers/AppPoolController.cs
using System.Diagnostics;
using DevUtility.Domain.Interfaces;
using DevUtility.Domain.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DevUtility.Controllers
{
    public class AppPoolController : Controller
    {
        private readonly ILogger<AppPoolController> _logger;
        private readonly IAppPoolService _appPoolService;

        public AppPoolController(ILogger<AppPoolController> logger,
            IAppPoolService appPoolService)
        {
            _logger = logger;
            _appPoolService = appPoolService;
        }

        public IActionResult Index([FromQuery(Name = "filter")] string filter)
        {
            var viewModel = _appPoolService.GetViewModel(filter);
            return View(viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

App/Controllers/HomeController.cs
using System.Diagnostics;
using DevUtility.Domain.Interfaces;
using DevUtility.Domain.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DevUtility.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAppPoolService _appPoolService;

        public HomeController(ILogger<HomeController> logger,
            IAppPoolService appPoolService)
        {
            _logger = logger;
            _appPoolService = appPoolService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

App/Views/AppPool/Index.cshtml
@model DevUtility.Domain.ViewModels.DevUtilityViewModel

@{
    ViewData["Title"] = "App Pools";
}

<div class="app-pool-filter">
    <form id="app-pool-filter">
        <div class="form-inner">
            <div class="form-group">
                <input type="text" class="form-control" id="filterFreeText" placeholder="" value="@Model.FilterQuery">
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
        </div>
    </form>
</div>

<div class="app-pool-list">
    @foreach (var appPool in Model.AppPools)
    {
        <div class="app-pool-list__app-pool @(appPool.IsStopped ? "app-pool--stopped stopped" : "app-pool--running running")" data-app-pool-name="@(appPool.Name)">
            <div class="app-pool__hgroup">
                <div class="app-pool__name">@appPool.Name</div>
                <div class="app-pool__state @(appPool.IsStopped ? "stopped border-fl" : "running border-fl")">@appPool.State</div>
            </div>
            <div class="app-pool__triggers">
                <div class="app-pool__trigger app-pool__trigger--start" data-api-action="start">
                    <div class="app-pool__trigger-container">
                        <div class="app-pool__trigger-name app-pool__trigger-name--start">
                            Start
                        </div>
                        @{
                            await Html.RenderPartialAsync("Partials/Iconography/_Start");
                        }
                    </div>
                </div>
                <div class="app-pool__trigger" data-api-action="stop">
                    <div class="app-pool__trigger-container">
                        <div class="app-pool__trigger-name">
                            Stop
                        </div>
                        @{
                            await Html.RenderPartialAsync("Partials/Iconography/_Stop");
                        }
                    </div>
                </div>
                <div class="app-pool__trigger" data-api-action="recycle">
                    <div class="app-pool__trigger-container">
                        <div class="app-pool__trigger-name">
                            Recycle
                        </div>
                        @{
                            await Html.RenderPartialAsync("Partials/Iconography/_Recycle");
                        }
                    </div>
                </div>

            </div>
        </div>
    }
</div>

App/Views/Home/Index.cshtml
@model DevUtility.Domain.ViewModels.DevUtilityViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="bg-body">
    
    Hello

</div>

App/Views/Shared/Partials/Iconography/_Recycle.cshtml
<svg class="ico-recycle" fill="#228096" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	 width="800px" height="800px" viewBox="0 0 528.919 528.918"
	 xml:space="preserve">
<g>
	<g>
		<path d="M70.846,324.059c3.21,3.926,8.409,3.926,11.619,0l69.162-84.621c3.21-3.926,1.698-7.108-3.372-7.108h-36.723
			c-5.07,0-8.516-4.061-7.427-9.012c18.883-85.995,95.625-150.564,187.207-150.564c105.708,0,191.706,85.999,191.706,191.706
			c0,105.709-85.998,191.707-191.706,191.707c-12.674,0-22.95,10.275-22.95,22.949s10.276,22.949,22.95,22.949
			c131.018,0,237.606-106.588,237.606-237.605c0-131.017-106.589-237.605-237.606-237.605
			c-116.961,0-214.395,84.967-233.961,196.409c-0.878,4.994-5.52,9.067-10.59,9.067H5.057c-5.071,0-6.579,3.182-3.373,7.108
			L70.846,324.059z"/>
	</g>
</g>
</svg>

App/Views/Shared/Partials/Iconography/_Start.cshtml
<svg class="ico-start" width="800px" fill="#228096" height="800px" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg">
    <path d="M59 61.922c0-9.768 13.016-15.432 22.352-11.615 10.695 7.017 101.643 58.238 109.869 65.076 8.226 6.838 10.585 17.695-.559 25.77-11.143 8.074-99.712 60.203-109.31 64.73-9.6 4.526-21.952-1.632-22.352-13.088-.4-11.456 0-121.106 0-130.873zm13.437 8.48c0 2.494-.076 112.852-.216 115.122-.23 3.723 3 7.464 7.5 5.245 4.5-2.22 97.522-57.704 101.216-59.141 3.695-1.438 3.45-5.1 0-7.388C177.488 121.952 82.77 67.76 80 65.38c-2.77-2.381-7.563 1.193-7.563 5.023z" stroke="#228096" fill-rule="evenodd" />
</svg>

App/Views/Shared/Partials/Iconography/_Stop.cshtml
<svg class="ico-stop" width="800px" height="800px" viewBox="0 0 24 24" fill="#228096" xmlns="http://www.w3.org/2000/svg">
    <path d="M6 6H18V18H6V6Z" stroke="#228096" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
</svg>

App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/x-icon" href="favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dev Utility App</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DevUtility.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="favicon.png" id="mast-logo" alt="Dev Utility" />
                    DevUtility
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="AppPool" asp-action="Index">App Pools</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DevUtility
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>